echo "-------------------------------------------"
echo "Tugas 1 SISOP Kelas-A "
echo "-------------------------------------------"
echo "Nama : Nayya Ramadhani P w"
echo "NPM : 21083010075 "
echo "-------------------------------------------"
echo "Notes :"
echo "-------------------------------------------"
echo "Halo Dunia "
echo "Ini adalah skrip Bash pertamaku di Linux"

