print("-" * 45 )
print(" Tugas 1 SISOP Kelas-A")
print("-" * 45)
print("Nama : Nayya Ramadhani P W")
print("NPM : 21083010075")
print("-" * 45 )
print("Notes")
print("-" * 45)
print("Halo dunia ")
print("Ini adalah skrip Bash pertamaku di Linux")

